In [1]:
import torch

In [2]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

 


In [5]:
query_2 = inputs[1]
attention_score_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attention_score_2[i] = torch.dot(query_2, x_i)
attention_score_2


tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [8]:
attn_weights_2_temp = attention_score_2/attention_score_2.sum()
print(attn_weights_2_temp)
print(attn_weights_2_temp.sum())

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
tensor(1.0000)


In [9]:
def softmax_naive(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)

attn_weights_2_naive = softmax_naive(attention_score_2)
print(attn_weights_2_naive)
print(attn_weights_2_naive.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)


In [10]:
attn_weights_2 = torch.softmax(attention_score_2, dim=0)
print(attn_weights_2)
print(attn_weights_2.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)


In [11]:
query_2 = inputs[1]

contex_vec_2 = torch.zeros(query_2.shape)
for i, x_i in enumerate(inputs):
    contex_vec_2 += attn_weights_2[i] * x_i
print(contex_vec_2)

tensor([0.4419, 0.6515, 0.5683])


In [12]:
attn_scores = torch.empty(6, 6)
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = torch.dot(x_i, x_j)
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [13]:
attn_scores = inputs @ inputs.T
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [15]:
attn_weights = torch.softmax(attn_scores, dim=1)
print(attn_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [16]:
print(attn_weights.sum(dim=1))

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [17]:
all_context_vecs = attn_weights @ inputs
print(all_context_vecs)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


In [19]:
x_2 = inputs[1]
d_in = 3
d_out = 2

In [21]:
w_query = torch.nn.Parameter(torch.randn(d_in, d_out), requires_grad=False)
w_key = torch.nn.Parameter(torch.randn(d_in, d_out), requires_grad=False)
w_val = torch.nn.Parameter(torch.randn(d_in, d_out), requires_grad=False)

In [23]:
query_2 = x_2 @ w_query
key_2 = x_2 @ w_key
val_2 = x_2 @ w_val
print(key_2, val_2)

tensor([ 0.0405, -2.2939]) tensor([ 0.3934, -1.0397])


In [24]:
keys = inputs @ w_key
vals = inputs @ w_val
print('keys.shape', keys.shape)
print('vals.shape', vals.shape)

keys.shape torch.Size([6, 2])
vals.shape torch.Size([6, 2])


In [26]:
attn_score_2 = query_2 @ keys.T
print(attn_score_2)

tensor([ 7.4407,  4.3438,  4.1664,  2.0499, -0.1962,  3.9487])


In [30]:
d_k = keys.shape[1]
attn_weights_2 = torch.softmax(attn_score_2/d_k**0.5, dim=-1)
print(attn_weights_2)
print(attn_weights_2.sum())

tensor([0.7565, 0.0847, 0.0747, 0.0167, 0.0034, 0.0640])
tensor(1.)


In [31]:
context_vec_2 = attn_weights_2 @ vals
print(context_vec_2)

tensor([ 0.4610, -0.5297])


In [42]:
import torch.nn as nn

class SelfAtttentionV1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.d_out = d_out
        self.w_key = nn.Parameter(torch.randn(d_in, d_out))
        self.w_query = nn.Parameter(torch.randn(d_in, d_out))        
        self.w_value = nn.Parameter(torch.randn(d_in, d_out)) 
    
    def forward(self, x):
        keys = x @ self.w_key
        queries = x @ self.w_query
        values = x @ self.w_value
        
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim=-1)
        
        context_vecs = attn_weights @ values
        return context_vecs
    
sa_v1 = SelfAtttentionV1(3, 2)
print(sa_v1(inputs))

tensor([[-1.2544, -0.2752],
        [-1.3024, -0.3520],
        [-1.3020, -0.3507],
        [-1.2687, -0.2915],
        [-1.2711, -0.2862],
        [-1.2775, -0.3101]], grad_fn=<MmBackward0>)


In [44]:
class SelfAtttentionV2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.w_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.w_query = nn.Linear(d_in, d_out, bias=qkv_bias)        
        self.w_value = nn.Linear(d_in, d_out, bias=qkv_bias) 
    
    def forward(self, x):
        keys = self.w_key(x)
        queries = self.w_query(x)
        values = self.w_value(x)
        
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim=-1)
        
        context_vecs = attn_weights @ values
        return context_vecs
    
sa_v2 = SelfAtttentionV2(3, 2)
print(sa_v2(inputs))

tensor([[-0.2754,  0.0925],
        [-0.2746,  0.0947],
        [-0.2746,  0.0947],
        [-0.2745,  0.0921],
        [-0.2742,  0.0940],
        [-0.2748,  0.0919]], grad_fn=<MmBackward0>)


In [48]:
keys = sa_v2.w_query(inputs)
queries = sa_v2.w_key(inputs)
attn_scores = queries @ keys.T
attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim=-1)
print(attn_weights)

tensor([[0.1599, 0.1758, 0.1762, 0.1589, 0.1722, 0.1571],
        [0.1683, 0.1688, 0.1688, 0.1639, 0.1656, 0.1646],
        [0.1683, 0.1688, 0.1687, 0.1640, 0.1655, 0.1647],
        [0.1687, 0.1668, 0.1668, 0.1659, 0.1651, 0.1667],
        [0.1679, 0.1666, 0.1665, 0.1664, 0.1657, 0.1669],
        [0.1687, 0.1678, 0.1678, 0.1649, 0.1652, 0.1656]],
       grad_fn=<SoftmaxBackward0>)


In [51]:
context_length = attn_scores.shape[0]
mask_simple = torch.tril(torch.ones(context_lenghts, context_length))
print(mask_simple)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


In [52]:
masked_simple = attn_weights * mask_simple
print(masked_simple)

tensor([[0.1599, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1683, 0.1688, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1683, 0.1688, 0.1687, 0.0000, 0.0000, 0.0000],
        [0.1687, 0.1668, 0.1668, 0.1659, 0.0000, 0.0000],
        [0.1679, 0.1666, 0.1665, 0.1664, 0.1657, 0.0000],
        [0.1687, 0.1678, 0.1678, 0.1649, 0.1652, 0.1656]],
       grad_fn=<MulBackward0>)


In [58]:
masked_simple_norm = masked_simple/masked_simple.sum(dim=-1, keepdims=True)
print(masked_simple_norm)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4991, 0.5009, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3327, 0.3337, 0.3336, 0.0000, 0.0000, 0.0000],
        [0.2525, 0.2497, 0.2496, 0.2483, 0.0000, 0.0000],
        [0.2015, 0.1999, 0.1999, 0.1998, 0.1989, 0.0000],
        [0.1687, 0.1678, 0.1678, 0.1649, 0.1652, 0.1656]],
       grad_fn=<DivBackward0>)


In [59]:
print(masked_simple_norm.sum(dim=-1))

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
       grad_fn=<SumBackward1>)


In [66]:
mask = torch.triu(torch.ones(context_length, context_length), diagonal=1)
masked = attn_scores.masked_fill(mask.bool(), -torch.inf)
print(masked)

tensor([[ 1.6012e-01,        -inf,        -inf,        -inf,        -inf,
                -inf],
        [ 7.6724e-02,  8.1533e-02,        -inf,        -inf,        -inf,
                -inf],
        [ 7.4395e-02,  7.8419e-02,  7.8147e-02,        -inf,        -inf,
                -inf],
        [ 2.9339e-02,  1.3211e-02,  1.2619e-02,  5.3151e-03,        -inf,
                -inf],
        [ 1.1602e-02,  4.8609e-04,  1.2230e-04, -5.0591e-04, -6.4550e-03,
                -inf],
        [ 5.5462e-02,  4.8191e-02,  4.7707e-02,  2.2826e-02,  2.5587e-02,
          2.9469e-02]], grad_fn=<MaskedFillBackward0>)


In [76]:
attn_weights = torch.softmax(masked/keys.shape[-1]**0.5, -1)
print(attn_weights)
print(attn_weights.sum(-1))

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4991, 0.5009, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3327, 0.3337, 0.3336, 0.0000, 0.0000, 0.0000],
        [0.2525, 0.2497, 0.2496, 0.2483, 0.0000, 0.0000],
        [0.2015, 0.1999, 0.1999, 0.1998, 0.1989, 0.0000],
        [0.1687, 0.1678, 0.1678, 0.1649, 0.1652, 0.1656]],
       grad_fn=<SoftmaxBackward0>)
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
       grad_fn=<SumBackward1>)


In [77]:
dropout = torch.nn.Dropout(0.5)
example = torch.ones(6, 6)
print(dropout(example))

tensor([[2., 0., 0., 0., 2., 0.],
        [2., 2., 2., 2., 0., 2.],
        [2., 0., 2., 2., 0., 0.],
        [0., 2., 0., 0., 2., 2.],
        [0., 0., 2., 2., 2., 0.],
        [2., 2., 0., 0., 2., 2.]])


In [78]:
print(dropout(attn_weights))

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.9983, 1.0017, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.6654, 0.6673, 0.6672, 0.0000, 0.0000, 0.0000],
        [0.5050, 0.4993, 0.4991, 0.0000, 0.0000, 0.0000],
        [0.4030, 0.0000, 0.3997, 0.3996, 0.3979, 0.0000],
        [0.3374, 0.3357, 0.0000, 0.3297, 0.0000, 0.0000]],
       grad_fn=<MulBackward0>)


In [95]:
class CasualAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.w_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.w_query = nn.Linear(d_in, d_out, bias=qkv_bias)        
        self.w_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout)
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1))
        
    def forward(self, x):
        b, num_tokens, d_in = x.shape
        keys = self.w_key(x)
        queries = self.w_query(x)
        values = self.w_value(x)
        
        attn_scores = queries @ keys.transpose(1, 2)
        attn_scores.masked_fill_(self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)
        
        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim=-1)
        attn_weights = self.dropout(attn_weights)
        
        context_vec = attn_weights @ values
        return context_vec

In [96]:
batch = torch.stack([inputs, inputs], dim=0)
print(batch.shape)

torch.Size([2, 6, 3])


In [98]:
context_length = batch.shape[1]
ca = CasualAttention(d_in, d_out, context_length, 0.0)
context_vec = ca(batch)
print(context_vec.shape)
print(context_vec)

torch.Size([2, 6, 2])
tensor([[[-4.0917e-02,  3.0951e-01],
         [ 4.6911e-05,  1.1021e-01],
         [ 1.4573e-02,  4.5926e-02],
         [ 1.4835e-02,  1.3604e-02],
         [ 3.3838e-02, -1.2378e-02],
         [ 2.2990e-02, -2.0141e-02]],

        [[-4.0917e-02,  3.0951e-01],
         [ 4.6911e-05,  1.1021e-01],
         [ 1.4573e-02,  4.5926e-02],
         [ 1.4835e-02,  1.3604e-02],
         [ 3.3838e-02, -1.2378e-02],
         [ 2.2990e-02, -2.0141e-02]]], grad_fn=<UnsafeViewBackward0>)


In [101]:
class MultiHeadAttentionWrapper(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        self.heads = nn.ModuleList([CasualAttention(d_in, d_out, context_length, dropout, qkv_bias) for _ in \
                                   range(num_heads)])
    
    def forward(self, x):
        return torch.cat([head(x) for head in self.heads], dim=-1)

In [105]:
context_length = batch.shape[1]
ma = MultiHeadAttentionWrapper(d_in, d_out, context_length, 0.0, 2)
context_vec = ma(batch)
print(context_vec.shape)
print(context_vec)

torch.Size([2, 6, 4])
tensor([[[-0.3399, -0.2629, -0.3469,  0.2974],
         [-0.1567, -0.0901, -0.4227,  0.2765],
         [-0.0977, -0.0359, -0.4354,  0.2652],
         [-0.0445,  0.0100, -0.4111,  0.2374],
         [-0.0764, -0.0387, -0.2987,  0.1821],
         [-0.0232,  0.0207, -0.3479,  0.1965]],

        [[-0.3399, -0.2629, -0.3469,  0.2974],
         [-0.1567, -0.0901, -0.4227,  0.2765],
         [-0.0977, -0.0359, -0.4354,  0.2652],
         [-0.0445,  0.0100, -0.4111,  0.2374],
         [-0.0764, -0.0387, -0.2987,  0.1821],
         [-0.0232,  0.0207, -0.3479,  0.1965]]], grad_fn=<CatBackward0>)


In [1]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        assert d_out % num_heads == 0, "d_out must be divisible by num_heads"
        
        self.d_out = d_out
        self.num_heads = num_heads
        self.head_dim = d_out//num_heads
        
        self.w_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.w_key = nn.Linear(d_in, d_out, bias=qkv_bias)        
        self.w_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.out_proj = nn.Linear(d_out, d_out)
        self.dropout = nn.Dropout(dropout)
        
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1))
    
    def forward(self, x):
        b, num_tokens, d_in = x.shape
        
        keys = self.w_key(x)
        values = self.w_value(x)
        queries = self.w_query(x)
        
        keys = keys.view(b, num_tokens, self.num_heads, self.head_dim)
        values = values.view(b, num_tokens, self.num_heads, self.head_dim)        
        queries = queries.view(b, num_tokens, self.num_heads, self.head_dim) 
        
        keys = keys.transpose(1, 2)
        values = values.transpose(1, 2)
        queries = queries.transpose(1, 2)
        
        attn_scores = queries @ keys.transpose(2, 3)
        
        mask_bool = self.mask.bool()[:num_tokens, :num_tokens]
        
        attn_scores.masked_fill_(mask_bool, -torch.inf)
        
        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim=-1)
        attn_weights = self.dropout(attn_weights)
        
        context_vec = (attn_weights @ values).transpose(1, 2)
        
        context_vec = context_vec.contiguous().view(b, num_tokens, self.d_out)
        contex_vec = self.out_proj(context_vec)
        
        return context_vec

NameError: name 'nn' is not defined

In [120]:
batch_size, context_length, d_in = batch.shape
d_out = 2
mha = MultiHeadAttention(d_in, d_out, context_length, 0.0, num_heads=2)
context_vecs = mha(batch)
print(context_vecs.shape)
print(context_vecs)

torch.Size([2, 6, 2])
tensor([[[-0.0967, -0.5155],
         [-0.2412, -0.4633],
         [-0.2911, -0.4457],
         [-0.2700, -0.3799],
         [-0.2931, -0.3600],
         [-0.2725, -0.3349]],

        [[-0.0967, -0.5155],
         [-0.2412, -0.4633],
         [-0.2911, -0.4457],
         [-0.2700, -0.3799],
         [-0.2931, -0.3600],
         [-0.2725, -0.3349]]], grad_fn=<ViewBackward0>)


In [122]:
a = torch.tensor([[[[0.2745, 0.6584, 0.2775, 0.8573],
                    [0.8993, 0.0390, 0.9268, 0.7388],
                    [0.7179, 0.7058, 0.9156, 0.4340]],

                   [[0.0772, 0.3565, 0.1479, 0.5331],
                    [0.4066, 0.2318, 0.4545, 0.9737],
                    [0.4606, 0.5159, 0.4220, 0.5786]]]])
print(a.shape)

torch.Size([1, 2, 3, 4])


In [124]:
print((a @ a.transpose(2, 3)).shape)
print(a @ a.transpose(2, 3))

torch.Size([1, 2, 3, 3])
tensor([[[[1.3208, 1.1631, 1.2879],
          [1.1631, 2.2150, 1.8424],
          [1.2879, 1.8424, 2.0402]],

         [[0.4391, 0.7003, 0.5903],
          [0.7003, 1.3737, 1.0620],
          [0.5903, 1.0620, 0.9912]]]])


In [128]:
first_head = a[0, 0, :, :]
print(first_head.shape)
print(first_head @ first_head.T)

torch.Size([3, 4])
tensor([[1.3208, 1.1631, 1.2879],
        [1.1631, 2.2150, 1.8424],
        [1.2879, 1.8424, 2.0402]])


In [129]:
second_head = a[0, 1, :, :]
print(second_head.shape)
print(second_head @ second_head.T)

torch.Size([3, 4])
tensor([[0.4391, 0.7003, 0.5903],
        [0.7003, 1.3737, 1.0620],
        [0.5903, 1.0620, 0.9912]])
