In [1]:
import pandas as pd
from io import StringIO

In [2]:
csv_data = """A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,"""

In [5]:
df = pd.read_csv(StringIO(csv_data))
df.head()

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [7]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

In [9]:
df.dropna(axis=0)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [10]:
df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [11]:
df.dropna(how='all')

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [16]:
df.dropna(thresh=4)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [18]:
df.dropna(subset=['C'])

A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

In [26]:
from sklearn.impute import SimpleImputer
import numpy as np

imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(df.values)
imputed_data = imp.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [49]:
df = pd.DataFrame([
['green', 'M', 10.1, 'class1'],
['red', 'L', 13.5, 'class2'],
['blue', 'XL', 15.3, 'class1']])
df.columns = ['color', 'size', 'price', 'classlabel']
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [47]:
sz_mapping = {'M':1, 'L': 2, 'XL': 3}
inv_sz_mapping = {v:k for k,v in sz_mapping.items()}
df.size = df['size'].map(sz_mapping)
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [48]:
class_mapping = {cls: idx for idx,cls in enumerate(df.classlabel.unique())}
df.classlabel = df['classlabel'].map(class_mapping)
df

color  size  price  classlabel
0  green     1   10.1           0
1    red     2   13.5           1
2   blue     3   15.3           0

In [53]:
df = pd.DataFrame([
['green', 'M', 10.1, 'class1'],
['red', 'L', 13.5, 'class2'],
['blue', 'XL', 15.3, 'class1']])
df.columns = ['color', 'size', 'price', 'classlabel']
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [54]:
from sklearn.preprocessing import LabelEncoder

cls_enc = LabelEncoder()
y = cls_enc.fit_transform(df.classlabel.values)
print(y)
y = cls_enc.inverse_transform(y)
print(y)

[0 1 0]
['class1' 'class2' 'class1']


In [57]:
df = pd.DataFrame([
['green', 'M', 10.1, 'class1'],
['red', 'L', 13.5, 'class2'],
['blue', 'XL', 15.3, 'class1']])
df.columns = ['color', 'size', 'price', 'classlabel']
df.size = df['size'].map(sz_mapping)
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [58]:
X = df[['color', 'size', 'price']].values
clr_enc = LabelEncoder()
X[:, 0] = clr_enc.fit_transform(X[:,0])
X

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [113]:
df = pd.DataFrame([
['green', 'M', 10.1, 'class1'],
['red', 'L', 13.5, 'class2'],
['blue', 'XL', 15.3, 'class1']])
df.columns = ['color', 'size', 'price', 'classlabel']
df.size = df['size'].map(sz_mapping)
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [114]:
from sklearn.preprocessing import OneHotEncoder
X = df[['color', 'size', 'price']].values
one_enc = OneHotEncoder(categories=[np.unique(X[:, 0])])
one_hot_encoded = one_enc.fit_transform(X[:, 0].reshape(-1, 1)).toarray()
X_encoded = np.hstack((one_hot_encoded, X[:, 1:]))

In [116]:
X_encoded

array([[0.0, 1.0, 0.0, 1, 10.1],
       [0.0, 0.0, 1.0, 2, 13.5],
       [1.0, 0.0, 0.0, 3, 15.3]], dtype=object)

In [117]:
df = pd.DataFrame([
['green', 'M', 10.1, 'class1'],
['red', 'L', 13.5, 'class2'],
['blue', 'XL', 15.3, 'class1']])
df.columns = ['color', 'size', 'price', 'classlabel']
df.size = df['size'].map(sz_mapping)
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [118]:
pd.get_dummies(df[['color', 'size', 'price']])

size  price  color_blue  color_green  color_red
0     1   10.1       False         True      False
1     2   13.5       False        False       True
2     3   15.3        True        False      False

In [119]:
pd.get_dummies(df[['color', 'size', 'price']], drop_first=True)

size  price  color_green  color_red
0     1   10.1         True      False
1     2   13.5        False       True
2     3   15.3        False      False

In [121]:
df_wine = pd.read_csv('https://archive.ics.uci.edu/'
'ml/machine-learning-databases/'
'wine/wine.data', header=None)
df_wine.columns = ['Class label', 'Alcohol',
                    'Malic acid', 'Ash',
                    'Alcalinity of ash', 'Magnesium',
                    'Total phenols', 'Flavanoids',
                    'Nonflavanoid phenols',
                    'Proanthocyanins',
                    'Color intensity', 'Hue',
                    'OD280/OD315 of diluted wines',
                    'Proline']
df_wine.head(5)

Class label  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0            1    14.23        1.71  2.43               15.6        127   
1            1    13.20        1.78  2.14               11.2        100   
2            1    13.16        2.36  2.67               18.6        101   
3            1    14.37        1.95  2.50               16.8        113   
4            1    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

In [127]:
len(df_wine['Class label'].unique())

3

In [131]:
from sklearn.model_selection import train_test_split

X, y = df_wine.iloc[:, 1:].values, df_wine.iloc[:, 0]
print(X.shape, y.shape)
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

(178, 13) (178,)


In [139]:
from sklearn.preprocessing import MinMaxScaler
min_sclr = MinMaxScaler()
x_trian_norm = min_sclr.fit_transform(x_train)
x_test_norm = min_sclr.fit_transform(x_test)

In [140]:
from sklearn.preprocessing import StandardScaler
sdc_sclr = StandardScaler()
x_train_std = sdc_sclr.fit_transform(x_train)
x_test_std = sdc_sclr.transform(x_test)