In [1]:
import torch

In [2]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [5]:
query_2 = inputs[1]
attention_score_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attention_score_2[i] = torch.dot(query_2, x_i)
attention_score_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [8]:
attn_weights_2_temp = attention_score_2/attention_score_2.sum()
print(attn_weights_2_temp)
print(attn_weights_2_temp.sum())

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
tensor(1.0000)


In [9]:
def softmax_naive(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)

attn_weights_2_naive = softmax_naive(attention_score_2)
print(attn_weights_2_naive)
print(attn_weights_2_naive.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)


In [10]:
attn_weights_2 = torch.softmax(attention_score_2, dim=0)
print(attn_weights_2)
print(attn_weights_2.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)


In [11]:
query_2 = inputs[1]

contex_vec_2 = torch.zeros(query_2.shape)
for i, x_i in enumerate(inputs):
    contex_vec_2 += attn_weights_2[i] * x_i
print(contex_vec_2)

tensor([0.4419, 0.6515, 0.5683])


In [12]:
attn_scores = torch.empty(6, 6)
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = torch.dot(x_i, x_j)
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [13]:
attn_scores = inputs @ inputs.T
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [15]:
attn_weights = torch.softmax(attn_scores, dim=1)
print(attn_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [16]:
print(attn_weights.sum(dim=1))

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [17]:
all_context_vecs = attn_weights @ inputs
print(all_context_vecs)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


In [19]:
x_2 = inputs[1]
d_in = 3
d_out = 2

In [21]:
w_query = torch.nn.Parameter(torch.randn(d_in, d_out), requires_grad=False)
w_key = torch.nn.Parameter(torch.randn(d_in, d_out), requires_grad=False)
w_val = torch.nn.Parameter(torch.randn(d_in, d_out), requires_grad=False)

In [23]:
query_2 = x_2 @ w_query
key_2 = x_2 @ w_key
val_2 = x_2 @ w_val
print(key_2, val_2)

tensor([ 0.0405, -2.2939]) tensor([ 0.3934, -1.0397])


In [24]:
keys = inputs @ w_key
vals = inputs @ w_val
print('keys.shape', keys.shape)
print('vals.shape', vals.shape)

keys.shape torch.Size([6, 2])
vals.shape torch.Size([6, 2])


In [26]:
attn_score_2 = query_2 @ keys.T
print(attn_score_2)

tensor([ 7.4407,  4.3438,  4.1664,  2.0499, -0.1962,  3.9487])


In [30]:
d_k = keys.shape[1]
attn_weights_2 = torch.softmax(attn_score_2/d_k**0.5, dim=-1)
print(attn_weights_2)
print(attn_weights_2.sum())

tensor([0.7565, 0.0847, 0.0747, 0.0167, 0.0034, 0.0640])
tensor(1.)


In [31]:
context_vec_2 = attn_weights_2 @ vals
print(context_vec_2)

tensor([ 0.4610, -0.5297])


In [42]:
import torch.nn as nn

class SelfAtttentionV1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.d_out = d_out
        self.w_key = nn.Parameter(torch.randn(d_in, d_out))
        self.w_query = nn.Parameter(torch.randn(d_in, d_out))        
        self.w_value = nn.Parameter(torch.randn(d_in, d_out)) 
    
    def forward(self, x):
        keys = x @ self.w_key
        queries = x @ self.w_query
        values = x @ self.w_value
        
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim=-1)
        
        context_vecs = attn_weights @ values
        return context_vecs
    
sa_v1 = SelfAtttentionV1(3, 2)
print(sa_v1(inputs))

tensor([[-1.2544, -0.2752],
        [-1.3024, -0.3520],
        [-1.3020, -0.3507],
        [-1.2687, -0.2915],
        [-1.2711, -0.2862],
        [-1.2775, -0.3101]], grad_fn=<MmBackward0>)


In [43]:
class SelfAtttentionV2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.w_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.w_query = nn.Linear(d_in, d_out, bias=qkv_bias)        
        self.w_value = nn.Linear(d_in, d_out, bias=qkv_bias) 
    
    def forward(self, x):
        keys = self.w_key(x)
        queries = self.w_query(x)
        values = self.w_value(x)
        
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim=-1)
        
        context_vecs = attn_weights @ values
        return context_vecs
    
sa_v1 = SelfAtttentionV2(3, 2)
print(sa_v1(inputs))

tensor([[-0.2591,  0.5418],
        [-0.2593,  0.5422],
        [-0.2592,  0.5421],
        [-0.2606,  0.5436],
        [-0.2583,  0.5402],
        [-0.2613,  0.5448]], grad_fn=<MmBackward0>)
